#!/bin/bash
#	/home/stats/bin/rrdstats/rrdgraph-cpu e -3600s
	/home/stats/bin/rrdstats/rrdgraph-cpu e1 -3600s
	/home/stats/bin/rrdstats/rrdgraph-cpu e2 -3600s
	/home/stats/bin/rrdstats/rrdgraph-cpu e3 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e4 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e5 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e6 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e7 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e8 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e9 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e10 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-cpu e11 -3600s

#	/home/stats/bin/rrdstats/rrdgraph-disk e -3600s
	/home/stats/bin/rrdstats/rrdgraph-disk e1 -3600s
	/home/stats/bin/rrdstats/rrdgraph-disk e2 -3600s
	/home/stats/bin/rrdstats/rrdgraph-disk e3 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e4 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e5 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e6 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e7 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e8 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e9 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e10 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-disk e11 -3600s

#	/home/stats/bin/rrdstats/rrdgraph-loadavg e -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e1 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e2 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e3 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e4 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e5 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e6 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e7 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e8 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e9 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e10 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-loadavg e11 -3600s

#	/home/stats/bin/rrdstats/rrdgraph-mem e -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e1 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e2 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e3 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e4 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e5 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e6 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e7 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e8 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e9 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e10 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-mem e11 -3600s

#	/home/stats/bin/rrdstats/rrdgraph-net e -3600s
	/home/stats/bin/rrdstats/rrdgraph-net e1 -3600s
	/home/stats/bin/rrdstats/rrdgraph-net e2 -3600s
	/home/stats/bin/rrdstats/rrdgraph-net e3 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e4 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e5 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e6 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e7 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e8 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e9 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e10 -3600s
#	/home/stats/bin/rrdstats/rrdgraph-net e11 -3600s

