#!/bin/bash
    rrdtool create /home/stats/data/`hostname -s`-loadavg.rrd --step 60 \
		DS:a1:GAUGE:240:0:U \
		DS:a5:GAUGE:240:0:U \
		DS:a15:GAUGE:240:0:U \
		RRA:AVERAGE:0.5:1:10000 \
		RRA:AVERAGE:0.5:5:4000 \
		RRA:AVERAGE:0.5:60:9000 
