#!/bin/bash
	if [[ $1 = 'e' ]]; then host='elephant'
	elif [[ $1 =  "e1" ]]; then host='elephant01'
	elif [[ $1 = "e2" ]]; then host='elephant02'
	elif [[ $1 = "e3" ]]; then host='elephant03'
	elif [[ $1 = "e4" ]]; then host='elephant04'
	elif [[ $1 = "e5" ]]; then host='elephant05'
	elif [[ $1 = "e6" ]]; then host='elephant06'
	elif [[ $1 = "e7" ]]; then host='elephant07'
	elif [[ $1 = "e8" ]]; then host='elephant08'
	elif [[ $1 = "e9" ]]; then host='elephant09'
	elif [[ $1 = "e10" ]]; then host='elephant10'
	elif [[ $1 = "e11" ]]; then host='elephant11'
	else echo "Host omitted or invalid."; exit
	fi

    /bin/mkdir -p ~/stats

	if [[ $2 = '' ]]; then start='-86400s'
		else start=$2
		fi

	if [[ $3 = '' ]]; then end='N'
		else end=$3
		fi

	if [[ $1 == 'e' ]]; then
		rrdtool graph  ~/stats/$host-disk.png --imgformat PNG \
			--title 'I/O Bandwidth Utilization ('$host')' \
			--width 1600 --height 800 \
			--start $start --end $end \
			DEF:e1r0=/home/stats/data/elephant01-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e1w0=/home/stats/data/elephant01-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e1r1=/home/stats/data/elephant01-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e1w1=/home/stats/data/elephant01-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e1t=e1r0,e1w0,+,e1r1,+,e1w1,+ \
			DEF:e2r0=/home/stats/data/elephant02-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e2w0=/home/stats/data/elephant02-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e2r1=/home/stats/data/elephant02-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e2w1=/home/stats/data/elephant02-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e2t=e2r0,e2w0,+,e2r1,+,e2w1,+ \
			DEF:e3r0=/home/stats/data/elephant03-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e3w0=/home/stats/data/elephant03-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e3r1=/home/stats/data/elephant03-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e3w1=/home/stats/data/elephant03-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e3t=e3r0,e3w0,+,e3r1,+,e3w1,+ \
			DEF:e4r0=/home/stats/data/elephant04-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e4w0=/home/stats/data/elephant04-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e4r1=/home/stats/data/elephant04-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e4w1=/home/stats/data/elephant04-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e4t=e4r0,e4w0,+,e4r1,+,e4w1,+ \
			DEF:e5r0=/home/stats/data/elephant05-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e5w0=/home/stats/data/elephant05-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e5r1=/home/stats/data/elephant05-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e5w1=/home/stats/data/elephant05-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e5t=e5r0,e5w0,+,e5r1,+,e5w1,+ \
			DEF:e6r0=/home/stats/data/elephant06-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e6w0=/home/stats/data/elephant06-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e6r1=/home/stats/data/elephant06-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e6w1=/home/stats/data/elephant06-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e6t=e6r0,e6w0,+,e6r1,+,e6w1,+ \
			DEF:e7r0=/home/stats/data/elephant07-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e7w0=/home/stats/data/elephant07-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e7r1=/home/stats/data/elephant07-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e7w1=/home/stats/data/elephant07-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e7t=e7r0,e7w0,+,e7r1,+,e7w1,+ \
			DEF:e8r0=/home/stats/data/elephant08-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e8w0=/home/stats/data/elephant08-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e8r1=/home/stats/data/elephant08-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e8w1=/home/stats/data/elephant08-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e8t=e8r0,e8w0,+,e8r1,+,e8w1,+ \
			DEF:e9r0=/home/stats/data/elephant09-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e9w0=/home/stats/data/elephant09-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e9r1=/home/stats/data/elephant09-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e9w1=/home/stats/data/elephant09-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e9t=e9r0,e9w0,+,e9r1,+,e9w1,+ \
			DEF:e10r0=/home/stats/data/elephant10-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e10w0=/home/stats/data/elephant10-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e10r1=/home/stats/data/elephant10-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e10w1=/home/stats/data/elephant10-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e10t=e10r0,e10w0,+,e10r1,+,e10w1,+ \
			DEF:e11r0=/home/stats/data/elephant11-disk-sda.rrd:MBRead:AVERAGE \
			DEF:e11w0=/home/stats/data/elephant11-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:e11r1=/home/stats/data/elephant11-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:e11w1=/home/stats/data/elephant11-disk-sdb.rrd:MBWritten:AVERAGE \
			CDEF:e11t=e11r0,e11w0,+,e11r1,+,e11w1,+ \
			LINE:e1t#00007f:"e1" \
			LINE:e2t#0000ff:"e2" \
			LINE:e3t#007f00:"e3" \
			LINE:e4t#007f7f:"e4" \
			LINE:e5t#007fff:"e5" \
			LINE:e6t#00ff00:"e6" \
			LINE:e7t#00ff7f:"e7" \
			LINE:e8t#00ffff:"e8" \
			LINE:e9t#7f0000:"e9" \
			LINE:e10t#7f007f:"e10" \
			LINE:e11t#7f00ff:"e11"
	else
		rrdtool graph  ~/stats/$host-disk.png --imgformat PNG \
			--title 'I/O Bandwidth Utilization ('$host')' \
			--width 1600 --height 800 \
			--start $start --end $end \
			DEF:r0=/home/stats/data/$host-disk-sda.rrd:MBRead:AVERAGE \
			DEF:w0=/home/stats/data/$host-disk-sda.rrd:MBWritten:AVERAGE \
			DEF:r1=/home/stats/data/$host-disk-sdb.rrd:MBRead:AVERAGE \
			DEF:w1=/home/stats/data/$host-disk-sdb.rrd:MBWritten:AVERAGE \
			LINE:r0#00007f:"sda-read" \
			LINE:w0#0000ff:"sda-write" \
			LINE:r1#007f00:"sdb-read" \
			LINE:w1#007f7f:"sdb-write"
	fi

