#!/bin/bash
	percent=`/usr/bin/mpstat 5 1 | /usr/bin/tail -n 1 | /bin/awk '{print $3+$4 ":" $5 ":" $6 ":" $7+$8 ":" $3+$4+$5+$6+$7+$8}'`
	host=`/bin/hostname -s`
	echo "rrdtool update /home/stats/data/$host-cpu.rrd N:$percent"
	/usr/bin/rrdtool update /home/stats/data/$host-cpu.rrd N:$percent
