#!/bin/bash
    sda=1
    sdb=1
    if (( ! $[$1]==1 )); then echo 'Device specification omitted or invalid.'; exit; fi

    io=`/bin/awk '/ '$1' / {print \$6*512 ":" \$10*512}' /proc/diskstats`
    host=`/bin/hostname -s`

    echo "rrdtool update /home/stats/data/$host-disk-$1.rrd N:$io"
    /usr/bin/rrdtool update /home/stats/data/$host-disk-$1.rrd N:$io
